In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [2]:
data = pd.DataFrame({
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age':    [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female'],
})
data

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [3]:
data['Gender'] = data['Gender'].map({'Male': 0, 'Female': 1})
data

   Weight  Height  Age  Gender
0      79    1.80   35       0
1      69    1.68   39       0
2      73    1.82   25       0
3      95    1.70   60       0
4      82    1.87   27       0
5      55    1.55   18       1
6      69    1.50   89       1
7      71    1.78   42       1
8      64    1.67   16       1
9      69    1.64   52       1

In [4]:
features = ['Height', 'Age', 'Gender']
x = data[features]
y = data['Weight']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

In [6]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [7]:
print("Coefficients:", dict(zip(features, model.coef_)))
print("Intercept:", model.intercept_)

Coefficients: {'Height': np.float64(51.32534925254518), 'Age': np.float64(0.31437156137321176), 'Gender': np.float64(-8.945241116888297)}
Intercept: -23.145791657098613

In [8]:
print("Predicted:", y_pred)
print("Actual:", y_test.values)

print("R2 score:", metrics.r2_score(y_test, y_pred))
print("MAE:", metrics.mean_absolute_error(y_test, y_pred))

Predicted: [68.42986119 53.12194667]
Actual: [69 55]
R2 score: 0.9606924228265161
MAE: 1.2240960681149318